### ISSUE TITLE
Minimum Viable Repo checklist

### ISSUE THREAD

**Issue by eigenhombre** [eigenhombre/abaft#1]
From https://gist.github.com/eigenhombre/204400c786f9dba3a8d3193d3ce1542a:

See also: http://johnj.com/posts/practices/

- [x] LICENSE file, including disclaimer
- [x] Automated build via Docker and GitHub Actions
- [x] Automated builds include unit tests
- [x] Automated builds include linting
- [x] Build badge
- [x] Artwork
- [ ] Versioned
- [x] Minimum snippet / example
- [ ] Link to API and/or `help` output
- [ ] Release procedure is automated
- [ ] Project available in public package manager
- [x] Track outstanding TODOs in Issues

**Comment by eigenhombre** [comment]
Remaining items are WONTDO for the moment.
